name: "Build container image according to repo structure"
description: "Build container image according to repo structure"

inputs:
  dockerfile:
    description: 'Location of dockerfile'
    required: true
  tag:
    description: ''
    required: true
  username:
    description: 'Username for registry'
    required: true
  password:
    description: 'Password for registry'
    required: true
  build-args:
    description: 'Any build args'
    required: false
    default: ''
  platform:
    description: 'Platform for container'
    required: false
    default: linux/amd64
  registry:
    description: 'Registry for container'
    required: false
    default: ghcr.io
outputs:
  docker-image-tag:
    description: "Full tag name of docker-image, though it was an input"
    value: ${{ inputs.tag }}

runs:
  using: "composite"
  steps:
    # Docker-provided build framework to build against other platforms
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platform }}
        pull: true
        push: true
        build-args: ${{ inputs.build-args }}
        tags: ${{ inputs.tag }}
        context: ${{ github.workspace }}
